src/PlatinDashboard.Presentation.MVC/Controllers/MidiasController.cs
using PlatinDashboard.Application.Interfaces;
using PlatinDashboard.Application.ViewModels.MidiaViewModels;
using PlatinDashboard.Presentation.MVC.MvcFilters;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PlatinDashboard.Presentation.MVC.Controllers
{
    public class MidiasController : BaseController
    {
        private readonly IVideoAppService _videoAppService;
        public MidiasController(IUserAppService userAppService,
                                  ICompanyAppService companyAppService,
                                  IVideoAppService videoAppService)
                                  : base(userAppService, companyAppService)
        {
            _videoAppService = videoAppService;
        }

        [HttpGet]
        [ClaimsAuthorize("UserType", "Admin,Subadmin,Manager")]
        public ActionResult Index()
        {
            var videosViewModels = _videoAppService.GetByCompany(CompanyUser.CompanyId);
            ViewBag.Cliente = (Session["userId"] == null ? "" : LoggedUser.Name);
            return View(videosViewModels);
        }

        [HttpGet]
        [ClaimsAuthorize("UserType", "Admin,Subadmin,Manager")]
        public ActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        [ClaimsAuthorize("UserType", "Admin,Subadmin,Manager")]
        public ActionResult Novo(VideoViewModel videoViewModel)
        {
            if (ModelState.IsValid)
            {
                videoViewModel.CompanyId = LoggedUser.CompanyId;
                videoViewModel.IsPublic = LoggedUser.UserType == "Admin";
                var addedVideo = _videoAppService.Add(videoViewModel);
                return Json(addedVideo);
            }
            return View(videoViewModel);
        }

        [ClaimsAuthorize("UserType", "Admin,Subadmin,Manager")]
        public ActionResult NovoVideo(HttpPostedFileBase video, int? videoId)
        {
            if (video == null || videoId == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var videoViewModel = new VideoViewModel(video, videoId.Value);
            _videoAppService.AddFile(videoViewModel);
            video.SaveAs(Server.MapPath(videoViewModel.FileName));
            return Json("success", string.Format("O video {0} foi cadastrado com sucesso!", video.FileName));
        }

        [HttpGet]
        [ClaimsAuthorize("UserType", "Admin,Subadmin,Manager")]
        public ActionResult Detalhes(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var videoViewModel = _videoAppService.GetById(id.Value);
            return View(videoViewModel);
        }

        [HttpPost]
        [ClaimsAuthorize("UserType", "Admin,Subadmin,Manager")]
        public ActionResult RemoverVideo(int? key)
        {
            if (key == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var videoViewModel = _videoAppService.GetById(key.Value);
            _videoAppService.RemoveFile(key.Value);
            if (System.IO.File.Exists(Server.MapPath(videoViewModel.FileName)))
            {
                System.IO.File.Delete(Server.MapPath(videoViewModel.FileName));
            }
            return Json("success", "A imagem foi removida com sucesso!");
        }

        [HttpGet]
        [ClaimsAuthorize("UserType", "Admin,Subadmin,Manager")]
        public ActionResult ModalRemover(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var video = _videoAppService.GetById(id.Value);
            if (video == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            return PartialView("_ModalRemoverVideo", video);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ClaimsAuthorize("UserType", "Admin,Subadmin,Manager")]
        public ActionResult Editar(VideoViewModel videoViewModel)
        {
            if (ModelState.IsValid)
            {
                videoViewModel = _videoAppService.Update(videoViewModel);
                return Json(new { updated = true, view = RenderPartialView("_Editar", videoViewModel) });
            }
            return Json(new { updated = false, view = RenderPartialView("_Editar", videoViewModel) });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ClaimsAuthorize("UserType", "Admin,Subadmin,Manager")]
        public ActionResult Remover(int? videoId)
        {
            if (videoId == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var videoViewModel = _videoAppService.GetById(videoId.Value);
            if (videoViewModel == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            _videoAppService.Remove(videoViewModel.VideoId);
            if (System.IO.File.Exists(Server.MapPath(videoViewModel.FileName)))
            {
                System.IO.File.Delete(Server.MapPath(videoViewModel.FileName));
            }
            return Json(new { deleted = true, videoId = videoViewModel.VideoId });
        }
    }
}

src/PlatinDashboard.Presentation.MVC/Views/Midias/Detalhes.cshtml
@using PlatinDashboard.Presentation.MVC.Helpers
@model PlatinDashboard.Application.ViewModels.MidiaViewModels.VideoViewModel
@{
    ViewBag.Title = "Criar novo Vídeo | Portal Legisig";
}
@section styles{
    @Styles.Render("~/coreui/ladda/css")
    @Styles.Render("~/coreui/file-input/css")
    <style>
        div.file-thumbnail-footer > div.file-thumb-progress.hide > div{
            display: none;
        }

        .file-input-ajax-new {
            width: 100%;
        }

        div.input-group.file-caption-main > div.input-group-btn > a {
            background-color: #4dbd74;
            color: white;
        }

        div.input-group.file-caption-main > div.input-group-btn > button {
            background-color: #f86c6b;
            color: white;
        }
    </style>
}
@section breadcrumb{
    <!-- Breadcrumb-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Home")">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Midias")">
                Mídias
            </a>
        </li>
        <li class="breadcrumb-item active">Novo Vídeo</li>
        <!-- Breadcrumb Menu-->
        <li class="breadcrumb-menu d-md-down-none">
            <div class="btn-group" role="group" aria-label="Button group">
                <a class="btn" href="javascript:void(0)">
                    Olá @User.Identity.Name !
                </a>
            </div>
        </li>
    </ol>
}
<div class="row">
    <div class="col-sm-8">
        <div class="card">
            <div class="card-header">
                <h4 style="display: inline-block">Detalhes do vídeo @Model.Title</h4>
                <a href="@Url.Action("Index", "Midias")" class="btn btn-primary pull-right">Cancelar</a>
            </div>
            <div class="card-body" id="form-content">
                <h5>Dados do Vídeo</h5>
                @Html.Partial("_Editar", Model)                             
            </div>
            <div class="card-body">
                <h5>Arquivo de Vídeo</h5>
                <div class="panel-body">
                    <div class="form-group">
                        <input id="video" name="video" class="file" type="file" multiple data-preview-file-type="any" data-upload-url="@Url.Action("NovoVideo", "Midias")">
                    </div>
                </div>
            </div>            
        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/unobstrusive")
    @Scripts.Render("~/coreui/file-input/script")
    @Scripts.Render("~/coreui/ladda/js")
    <script src="~/Scripts/viewsjs/details.js"></script>
    <script src="~/Scripts/viewsjs/videoindex.js"></script>
    <script>
        $('#video').fileinput({
            language: 'pt-BR',
            allowedFileExtensions: ['mp4', 'mkv', 'avi', '3gp'],
            showCancel: false,
            fileActionSettings: { showZoom: false, uploadIcon: '<i class="fa fa-upload "></i>', removeIcon: '<i class="fa fa-trash-o "></i>', },
            maxFileCount: 1,
            maxFileSize: 81920,
            validateInitialCount: true,            
            overwriteInitial: false,
            initialPreviewAsData: true,
            uploadExtraData: { videoId: @Model.VideoId },
            initialPreview: [
                @if (Model.FileName != null)
                {
                    var path = Model.FileName;
                    @:'@Url.Content(path)',
                }
            ],
            initialPreviewConfig: [
                { type: "video", filetype: "video/mp4", caption: "@Model.Title", url: "@Url.Action("RemoverVideo", "Midias")", key: @Model.VideoId }
            ],
        })
        .on('fileuploaded', function(event, data, previewId, index) {
            location.reload();
        });
    </script>
}

src/PlatinDashboard.Presentation.MVC/Views/Midias/Index.cshtml
@model IEnumerable<PlatinDashboard.Application.ViewModels.MidiaViewModels.VideoViewModel>
@{
    ViewBag.Title = "Mídias | Portal Legisig";
}
@section styles{
    @Styles.Render("~/coreui/ladda/css")
    @Styles.Render("~/coreui/datatables/css")
}
@section breadcrumb{
    <!-- Breadcrumb-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Home")">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Mídias</li>
        <!-- Breadcrumb Menu-->
        <li class="breadcrumb-menu d-md-down-none">
            <div class="btn-group" role="group" aria-label="Button group">
                <a class="btn" href="javascript:void(0)">
                    Olá @User.Identity.Name !
                </a>
            </div>
        </li>
    </ol>
}
<div class="card">
    <div class="card-header">
        <h4 style="display: inline-block">Vídeos Cadastrados</h4>
        <a href="@Url.Action("Novo", "Midias")" class="btn btn-primary pull-right">
            <i class="fa icon-plus"></i> Criar
        </a>
    </div>
    <div class="card-body">
        <table class="table table-responsive-sm table-hover table-outline mb-0" id="videosTable">
            <thead class="thead-light">
                <tr>
                    <th class="text-center">Título</th>
                    <th class="text-center">Descrição</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var video in Model)
                {
                    <tr id="video-row-@video.VideoId">
                        <td class="text-center">
                            @video.Title
                        </td>
                        <td class="text-center">
                            @video.Description
                        </td>
                        <td class="text-right">
                            <a class="btn btn-success" href="@Url.Action("Detalhes", "Midias", new { id = video.VideoId })">
                                <i class="fa fa-search-plus "></i>
                            </a>
                            <a class="btn btn-danger ladda-button" data-style="zoom-out" href="javascript:void(0)" onclick="showDeleteModal(this, '@video.VideoId')">
                                <i class="fa fa-trash-o "></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@section modals{
    <div id="modal-section"></div>
}
@section scripts{
    @Scripts.Render("~/bundles/unobstrusive")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/coreui/ladda/js")
    @Scripts.Render("~/coreui/datatables/js")
    <script src="~/Scripts/viewsjs/index.js"></script>
    <script src="~/Scripts/viewsjs/videoindex.js"></script>
    <script src="~/Scripts/viewsjs/changeclient.js"></script>
    <script>
        $(document).ready(function () {
            loadClientes();
            initializeVideoTable();
        });
    </script>
}

src/PlatinDashboard.Presentation.MVC/Views/Midias/Novo.cshtml
@using PlatinDashboard.Presentation.MVC.Helpers
@model PlatinDashboard.Application.ViewModels.MidiaViewModels.VideoViewModel
@{
    ViewBag.Title = "Criar novo Vídeo | Portal Legisig";
}
@section styles{
    @Styles.Render("~/coreui/file-input/css")
    <style>
        .file-input-ajax-new{
            width: 100%;
        }
        div.input-group.file-caption-main > div.input-group-btn > a {
            background-color: #4dbd74;
            color: white;
        }
        div.input-group.file-caption-main > div.input-group-btn > button {
            background-color: #f86c6b;
            color: white;
        }
    </style>
}
@section breadcrumb{
    <!-- Breadcrumb-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Home")">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Midias")">
                Mídias
            </a>
        </li>
        <li class="breadcrumb-item active">Novo Vídeo</li>
        <!-- Breadcrumb Menu-->
        <li class="breadcrumb-menu d-md-down-none">
            <div class="btn-group" role="group" aria-label="Button group">
                <a class="btn" href="javascript:void(0)">
                    Olá @User.Identity.Name !
                </a>
            </div>
        </li>
    </ol>
}
<div class="row">
    <div class="col-sm-8">
        <div class="card">
            <div class="card-header">
                <h4 style="display: inline-block">Cadastrar novo Vídeo</h4>
                <a href="@Url.Action("Index", "Midias")" class="btn btn-primary pull-right">Cancelar</a>
            </div>
            <div class="card-body" id="form-content">
                <h5>Dados do Vídeo</h5>
                @using (Ajax.BeginForm("Novo", "Midias", new AjaxOptions { OnBegin = "DesabilitarForm()", OnFailure = "console.log(data)", OnSuccess = "CarregarModal(data), console.log(data);", UpdateTargetId = "form-content", InsertionMode = InsertionMode.InsertAfter, HttpMethod = "Post" }, new { @class = "form-horizontal", @id = "Video-Form" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="row">
                        <div class="form-group col-sm-12">
                            @Html.LabelFor(model => model.Title)
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", placeholder = "Título do vídeo" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "error invalid-feedback" })
                        </div>
                        <div class="form-group col-sm-12">
                            @Html.LabelFor(model => model.Description)
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control", placeholder = "Descrição do vídeo" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "error invalid-feedback" })
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success">Criar</button>
                    <a href="@Url.Action("Index", "Midias")" class="btn btn-danger">Cancelar</a>
                }
            </div>
        </div>
    </div>
</div>
@section modals{
    @Html.Partial("_ModalVideoFile")
}
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/unobstrusive")
    @Scripts.Render("~/coreui/file-input/script")
    <script>
        $('#video').fileinput({
            language: 'pt-BR',
            allowedFileExtensions: ['mp4', 'mkv', 'avi', '3gp'],
            showCancel: false,
            fileActionSettings: { showUpload: false, showZoom: false, uploadIcon: '<i class="fa fa-upload "></i>', removeIcon: '<i class="fa fa-trash-o "></i>', },
            maxFileCount: 1,
            maxFileSize: 81920
        });

        $('#video').on('filebatchuploadcomplete', function (event, files, extra) {
            setTimeout(function () {
                $('#CadastrarVideo').modal("hide");
                $('#Produto-Form button').attr('disabled', 'disabled');
            }, 1500);
            setTimeout(function () { window.location.replace("/Midias"); }, 3000);
        });

        function DesabilitarForm() {
            $("#Video-Form input").prop("disabled", true);
            $("#Video-Form textarea").prop("disabled", true);
            $('#Video-Form button').button("loading");
        }

        function CarregarModal(video) {
            $('#Video-Form button').button("reset");
            $('#video').fileinput('refresh', { uploadExtraData: { videoId: video.VideoId } });
            $('#CadastrarVideo').modal(({ backdrop: 'static', keyboard: false }));
        }
    </script>
}

src/PlatinDashboard.Presentation.MVC/Views/Midias/_Editar.cshtml
@using PlatinDashboard.Presentation.MVC.Helpers
@model PlatinDashboard.Application.ViewModels.MidiaViewModels.VideoViewModel
<div class="card-body" id="form-content">
    @using (Ajax.BeginForm("Editar", new { @controller = "Midias" },
        new AjaxOptions
        {
            OnSuccess = "editVideoCallBack",
            OnFailure = "editVideoFailed()"
        },
                          new { @id = "edit-form" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.VideoId)
        <div class="row">
            <div class="form-group col-sm-12">
                @Html.LabelFor(model => model.Title)
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", placeholder = "Título do vídeo" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "error invalid-feedback" })
            </div>
            <div class="form-group col-sm-12">
                @Html.LabelFor(model => model.Description)
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", placeholder = "Descrição do vídeo" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "error invalid-feedback" })
            </div>
        </div>
        <button type="submit" class="btn btn-success ladda-button" data-style="zoom-out" id="edit-btn" onclick="submitForm(this, 'edit-form')">
            <span class="ladda-label">Alterar</span>
        </button>
    }
</div>

src/PlatinDashboard.Presentation.MVC/Views/Midias/_ModalRemoverVideo.cshtml
@model PlatinDashboard.Application.ViewModels.MidiaViewModels.VideoViewModel
<div class="modal fade" id="delete-video-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-danger" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Remover vídeo @Model.Title</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="delete-video-modal-message">Você tem certeza que deseja remover o vídeo @Model.Title?</p>
            </div>
            @using (Ajax.BeginForm("Remover", new { @controller = "Midias" },
                                    new AjaxOptions
                                    {
                                        OnSuccess = "deleteVideoCallBack",
                                        OnFailure = "deleteVideoFailed()"
                                    }
                                    ,
                                    new { @id = "delete-video-form" }))
            {
                <div class="modal-footer">
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.VideoId, new { id = "delete-video-id" })
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-danger ladda-button" data-style="zoom-out" onclick="submitForm(this, 'delete-video-form')">Confirmar</button>
                </div>
            }
        </div>
    </div>
</div>

src/PlatinDashboard.Presentation.MVC/Views/Midias/_ModalVideoFile.cshtml
<!-- Modal -->
<div class="modal fade" id="CadastrarVideo" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title-site text-center">Cadastrar Vídeo</h3>
            </div>
            <div class="modal-footer" style="margin-top:0;">
                
                    <input id="video" name="video" class="file" type="file" multiple data-preview-file-type="any" data-upload-url="@Url.Action("NovoVideo", "Midias")">
                
            </div>
        </div>
    </div>
</div>