src/PlatinDashboard.Presentation.MVC/Models/Parametros.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PlatinDashboard.Presentation.MVC.Models
{
    public class Parametros
    {
        public int Id { get; set; }
        public string Capitulo { get; set; }
        public string Item { get; set; }
        public string Parametro { get; set; }
        public int? Obrigacao { get; set; }
        public int IDLegisGeral { get; set; }
        public string IDCliente { get; set; }
        public int? Numero { get; set; }
        public int? Aplicavel { get; set; }
        public string lei { get; set; }
        public string param { get; set; }
        public int? Conhecimento { get; set; }

    }
}

src/PlatinDashboard.Presentation.MVC/Controllers/ParametrosController.cs
using PlatinDashboard.Presentation.MVC.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using static PlatinDashboard.Presentation.MVC.Models.IdentityModels;

namespace PlatinDashboard.Presentation.MVC.Controllers
{
    public class ParametrosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Parametros
        public ActionResult Index(int? pagina, int id, string busca)
        {
            var parametros = new List<Parametros>();
            parametros = db.Parametros.OrderByDescending(p => p.Id).Where(p => p.IDLegisGeral == id).ToList();
            ViewBag.param = parametros;
            return View();
        }
    }
}

src/PlatinDashboard.Presentation.MVC/Views/Parametros/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<PlatinDashboard.Presentation.MVC.Models.Parametros>
@{
    ViewBag.Title = "LegiSig| Portal Legisig";
}
@section styles{
    @Styles.Render("~/coreui/ladda/css")
    @Styles.Render("~/coreui/datatables/css")
}
@section breadcrumb{
    <!-- Breadcrumb-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Home")">Painel Geral</a>
        </li>
        <li class="breadcrumb-item active">Parametros</li>
        <!-- Breadcrumb Menu-->
        <li class="breadcrumb-menu d-md-down-none">
            <div class="btn-group" role="group" aria-label="Button group">
                <a class="btn" href="javascript:void(0)">
                    Olá @User.Identity.Name !
                </a>
            </div>
        </li>
    </ol>
}

<div class="card">
    <div class="card-header">
        <h4 style="display: inline-block">Listagem de Vendas</h4>
        <a href="@Url.Action("Index", "PDV")" class="btn btn-primary pull-right">
            <i class="fa icon-plus"></i> Caixas
        </a>
    </div>
    <div class="card-body">
        <table class="table table-striped table-bordered table-responsive-sm datatable dataTable no-footer" id="companiesTable">
            <thead>
                <tr>
                    <th class="text-center"><span>Capitulo</span></th>
                    <th class="text-center"><span>Item</span></th>
                    <th class="text-center"><span>Parametro</span></th>
                    @*<th class="text-center"><span>Municipio</span></th>
                    <th class="text-center"><span>País</span></th>
                    <th class="text-center"><span>Orgão</span></th>
                    <th class="text-center"><span>Numero</span></th>
                    <th class="text-center"><span>Ano</span></th>
                    <th class="text-center"><span>Tipo</span></th>
                    <th class="text-center"><span>Ementa</span></th>
                    <th class="text-center"><span>Tema</span></th>
                    <th class="text-center"><span>Situação</span></th>*@
                    <th class="text-center"><span>Ação</span></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var company in ViewBag.param)
                {
                    <tr id="company-row-@company.Id">
                        @*<td class="text-center">
                                <span class="label label-large label-@(company.Id > 0  ? "success" : "danger")">#@company.Id</span>
                            </td>*@
                        <td>@company.Capitulo</td>
                        <td>@company.Item</td>
                        <td>@company.Parametro</td>
                        @*<td>@company.Municipio</td>
                        <td>@company.Pais</td>
                        <td>@company.Orgao</td>
                        <td>@company.Numero</td>
                        <td>@company.Ano</td>
                        <td>@company.Tipo</td>
                        <td>@company.Ementa</td>
                        <td>@company.Tema</td>
                        <td>@company.lei</td>*@
                        <td class="text-center">
                            <a href="@Url.Action("Index", "Parametros", new { id=company.Id })" class="btn btn-success">Parametros</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section modals{
    <div id="modal-section"></div>
}
@section scripts{
    @Scripts.Render("~/bundles/unobstrusive")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/coreui/ladda/js")
    @Scripts.Render("~/coreui/datatables/js")
    <script src="~/Scripts/viewsjs/index.js"></script>
    <script src="~/Scripts/viewsjs/companyindex.js"></script>
    <script>
    $(document).ready(function () {
        initializeCompanyTable();
    });
    </script>
}