src/PlatinDashboard.Presentation.MVC/Models/Sistemas.cs
namespace PlatinDashboard.Presentation.MVC.Models
{
    public class Sistemas
    {
        public int Id { get; set; }
        public string Sistema { get; set; }
        public Sistemas(int id)
        {
            this.Id = id;
        }
        public Sistemas()
        {

        }

    }

}

src/PlatinDashboard.Presentation.MVC/Controllers/SistemasController.cs
using PlatinDashboard.Infra.Data.Context;
using System.Web.Mvc;

namespace PlatinDashboard.Presentation.MVC.Controllers
{
    public class SistemasController : Controller
    {
        private PortalContext db = new PortalContext();

        // GET: Sistemas
        public ActionResult Index()
        {
            return View();
        }

        // GET: Sistemas/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Sistemas sistemas = db.Sistemas.Find(id);
        //    if (sistemas == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(sistemas);
        //}

        //// GET: Sistemas/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Sistemas/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Sistema")] Sistemas sistemas)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Sistemas.Add(sistemas);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(sistemas);
        //}

        //// GET: Sistemas/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Sistemas sistemas = db.Sistemas.Find(id);
        //    if (sistemas == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(sistemas);
        //}

        //// POST: Sistemas/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,Sistema")] Sistemas sistemas)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(sistemas).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(sistemas);
        //}

        //// GET: Sistemas/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Sistemas sistemas = db.Sistemas.Find(id);
        //    if (sistemas == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(sistemas);
        //}

        //// POST: Sistemas/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Sistemas sistemas = db.Sistemas.Find(id);
        //    db.Sistemas.Remove(sistemas);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

src/PlatinDashboard.Presentation.MVC/Views/Sistemas/Create.cshtml
@model Model.Entity.Sistemas

@{
    ViewBag.Title = "Create";
}

@section styles{
    @Styles.Render("~/coreui/ladda/css")
    @Styles.Render("~/coreui/datatables/css")
}
@section breadcrumb{
    <!-- Breadcrumb-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Home")">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Sistemas</li>
        <!-- Breadcrumb Menu-->
        <li class="breadcrumb-menu d-md-down-none">
            <div class="btn-group" role="group" aria-label="Button group">
                <a class="btn" href="javascript:void(0)">
                    Olá @User.Identity.Name !
                </a>
            </div>
        </li>
    </ol>
}
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
<div class="card">
    <div class="card-header">
        <h4 style="display: inline-block">Cadastro de Sistemas</h4>
        <a href="@Url.Action("Index", "Sistemas")" class="btn btn-primary pull-right">
            <i class="fa icon-plus"></i> Voltar
        </a>
    </div>
    <div class="card-body">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Cadastrar</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    @Html.LabelFor(model => model.Sistema, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Sistema, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Sistema, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Gravar" class="btn btn-danger" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

src/PlatinDashboard.Presentation.MVC/Views/Sistemas/Delete.cshtml
@model Model.Entity.Sistemas

@{
    ViewBag.Title = "Delete";
}

@section styles{
    @Styles.Render("~/coreui/ladda/css")
    @Styles.Render("~/coreui/datatables/css")
}
@section breadcrumb{
    <!-- Breadcrumb-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Home")">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Sistemas</li>
        <!-- Breadcrumb Menu-->
        <li class="breadcrumb-menu d-md-down-none">
            <div class="btn-group" role="group" aria-label="Button group">
                <a class="btn" href="javascript:void(0)">
                    Olá @User.Identity.Name !
                </a>
            </div>
        </li>
    </ol>
}
<link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
<div class="card">
    <div class="card-header">
        <h4 style="display: inline-block">Cadastro de Sistemas</h4>
        <a href="@Url.Action("Index", "Sistemas")" class="btn btn-primary pull-right">
            <i class="fa icon-plus"></i> Voltar
        </a>
    </div>
    <div class="card-body">

        <h3> Deseja excluir o registro abaixo ?</h3>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Sistema)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Sistema)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Excluir" class="btn btn-danger" />
                </div>
            }
        </div>

    </div>
</div>

src/PlatinDashboard.Presentation.MVC/Views/Sistemas/Details.cshtml
@model Model.Entity.Sistemas

@{
    ViewBag.Title = "Details";
}
@section styles{
    @Styles.Render("~/coreui/ladda/css")
    @Styles.Render("~/coreui/datatables/css")
}
@section breadcrumb{
    <!-- Breadcrumb-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Home")">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Sistemas</li>
        <!-- Breadcrumb Menu-->
        <li class="breadcrumb-menu d-md-down-none">
            <div class="btn-group" role="group" aria-label="Button group">
                <a class="btn" href="javascript:void(0)">
                    Olá @User.Identity.Name !
                </a>
            </div>
        </li>
    </ol>
}
<link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
<div class="card">
    <div class="card-header">
        <h4 style="display: inline-block">Cadastro de Sistemas</h4>
        <a href="@Url.Action("Index", "Sistemas")" class="btn btn-primary pull-right">
            <i class="fa icon-plus"></i> Voltar
        </a>
    </div>
    <div class="card-body">

        <div>
            <h4>Detalhes</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Sistema)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Sistema)
                </dd>

            </dl>
        </div>
        <p>
            <a href="@Url.Action("Edit", "Sistemas", new { id = Model.Id })" class="btn btn-warning pull-right">
                <i class="fa icon-plus"></i> Editar
            </a>
        </p>
    </div>
</div>

src/PlatinDashboard.Presentation.MVC/Views/Sistemas/Edit.cshtml
@model Model.Entity.Sistemas

@{
    ViewBag.Title = "Edit";
}

@section styles{
    @Styles.Render("~/coreui/ladda/css")
    @Styles.Render("~/coreui/datatables/css")
}
@section breadcrumb{
    <!-- Breadcrumb-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Home")">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Sistemas</li>
        <!-- Breadcrumb Menu-->
        <li class="breadcrumb-menu d-md-down-none">
            <div class="btn-group" role="group" aria-label="Button group">
                <a class="btn" href="javascript:void(0)">
                    Olá @User.Identity.Name !
                </a>
            </div>
        </li>
    </ol>
}
<link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
<div class="card">
    <div class="card-header">
        <h4 style="display: inline-block">Cadastro de Sistemas</h4>
        <a href="@Url.Action("Index", "Sistemas")" class="btn btn-primary pull-right">
            <i class="fa icon-plus"></i> Voltar
        </a>
    </div>
    <div class="card-body">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Sistemas</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)


                <div class="form-group">
                    @Html.LabelFor(model => model.Sistema, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Sistema, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Sistema, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-6">
                        <input type="submit" value="Gravar" class="btn btn-danger" />
                    </div>
                </div>
            </div>
        }
        <p>
            <a href="@Url.Action("Edit", "Sistemas", new { id = Model.Id })" class="btn btn-warning pull-right">
                <i class="fa icon-plus"></i> Editar
            </a>
        </p>
    </div>
</div>

src/PlatinDashboard.Presentation.MVC/Views/Sistemas/Index.cshtml
@model IEnumerable<Model.Entity.Sistemas>

@{
    ViewBag.Title = "Sistemas | Portal Legisig";
}
@section styles{
    @Styles.Render("~/coreui/ladda/css")
    @Styles.Render("~/coreui/datatables/css")
}
@section breadcrumb{
    <!-- Breadcrumb-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Home")">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Sistemas</li>
        <!-- Breadcrumb Menu-->
        <li class="breadcrumb-menu d-md-down-none">
            <div class="btn-group" role="group" aria-label="Button group">
                <a class="btn" href="javascript:void(0)">
                    Olá @User.Identity.Name !
                </a>
            </div>
        </li>
    </ol>
}
<link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />

<div class="card">
    <div class="card-header">
        <h4 style="display: inline-block">Cadastro de Sistemas</h4>
        <a href="@Url.Action("Create", "Sistemas")" class="btn btn-success pull-right">
            <i class="fa icon-plus"></i> Cadastrar
        </a>

    </div>
    <div class="card-body">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Sistema)
                </th>
                <th class="text-right">Ações</th>

            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sistema)
                    </td>
                    <td class="text-right">
                        <a class="btn btn-success" data-toggle="tooltip" data-placement="right" ToolTip="My tooltip text" href="@Url.Action("Edit", "Sistemas", new { id = item.Id })">
                            <i class="fa fa-edit "></i>
                        </a>
                        <a class="btn btn-warning" href="@Url.Action("Details", "Sistemas", new { id = item.Id })">
                            <i class="fa fa-file-archive-o "></i>
                        </a>
                        <a class="btn btn-danger" href="@Url.Action("Delete", "Sistemas", new { id = item.Id })">
                            <i class="fa fa-trash-o"></i>
                        </a>
                    </td>
                </tr>
            }

        </table>
    </div>